name: Greetings

on: 
   pull_request_target:
      types: [opened, labeled]
permissions:
   pull-requests: write
   contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thanks for contributing to this project, hope you liked the guide provided to facilitate easy contribution.'
